name: Waka Readme

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          API_BASE_URL: https://lab-wakapi.petri.zip/api
          TIME_RANGE: last_30_days
          LANG_COUNT: 7
          BLOCKS: "░▒▓█"
          SHOW_TIME: true
          SHOW_TOTAL: true
          CODE_LANG: rust
          COMMIT_MESSAGE: "chore: atualizar estatisticas da semana"
